apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.sample.com
    http:
      paths:
      - backend:
          serviceName: podinfo-svc
          servicePort: 9898